version: '3.1'

services:

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: suscrofa
      POSTGRES_USER: suscrofa_adm
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: 